### PR TITLE
st1 [2190][IMP] stock_view_adj_rpl

### PR DESCRIPTION
**Pull request by tack-yabeQuartile**
[2190](https://www.quartile.co/web#id=2190&action=771&model=project.task&view_type=form&menu_id=)

* add two columns about deadlines for product on the list view of Lot/Serials
* Users can search the records of Lot/Serial with specific date and can group the records by date.

### CODE REVIEW

**Comment by tack-yabeQuartile** [comment]
TODO
* translate

**Comment by tack-yabeQuartile** [comment]
TODO
- [x] translation
- [x] pre-commit

**Comment by tack-yabeQuartile** [comment]
TODO
more check is needed to avoid travis error. Now travis says expiry_rpl module is not called appropriately.

**Comment by yostashiro** [comment]
@tack-yabeQuartile I think this should be handled by updating stock_lot_expiry_rpl.  We should not add a lot of custom module dependencies to the xxx_view_adj modules.

**Comment by yostashiro** [comment]
Closing this in preference of https://github.com/qrtl/rpl-custom/pull/195.

**Pull request closed without merging**
